# Generated by Django 2.2.8 on 2020-10-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_create_kakao_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteInfo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("depart_address", models.CharField(help_text="출발지 주소", max_length=50)),
                ("arrive_address", models.CharField(help_text="도착지 주소", max_length=50)),
                ("depart_at", models.DateTimeField(help_text="출발 시각")),
                ("arrive_at", models.DateTimeField(help_text="도착 시각")),
                (
                    "transport",
                    models.CharField(
                        choices=[("walk", "도보"), ("bus", "버스"), ("taxi", "택시"), ("own", "자가용"), ("other", "그 외")],
                        help_text="이동 수단",
                        max_length=5,
                    ),
                ),
                ("finished_at", models.DateTimeField(help_text="귀가 종료 시각", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kakao_user_id",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="authentication.KakaoUser",
                    ),
                ),
            ],
            options={"verbose_name": "유저의 귀가 정보", "db_table": "route_info"},
        ),
    ]
