# Generated by Django 2.2.8 on 2020-10-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_create_kakao_user"),
        ("home", "0001_create_route_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyPhoneNumber",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("owner_name", models.CharField(help_text="전화번호 주인 이름", max_length=10)),
                ("phone_number", models.CharField(help_text="전화번호", max_length=13)),
                (
                    "kakao_user_id",
                    models.ForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="authentication.KakaoUser"
                    ),
                ),
            ],
            options={"verbose_name": "긴급연락처", "db_table": "emergency_phone_number"},
        ),
    ]
