# Generated by Django 2.2.8 on 2020-10-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KakaoUser",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kakao_id", models.CharField(max_length=30, unique=True)),
                ("username", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("gender", models.CharField(choices=[("female", "여성")], default="female", max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "카카오 사용자 정보", "db_table": "kakao_user"},
        ),
    ]
